---
version: '2'
services:
  postgres:
    image: postgres:9.6
    hostname: bitwrap-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bitwrap
      POSTGRES_PASSWORD: bitwrap
      POSTGRES_DB: bitwrap

  rabbit:
    image: rabbitmq:3-management
    hostname: bitwrap-rabbit
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: bitwrap
      RABBITMQ_DEFAULT_PASS: bitwrap

  txbitwrap:
    image: stackdump/txbitwrap:dev
    hostname: txbitwrap
    command: api
    ports:
      - 8080:8080
    build:
      context: ./
    environment:
      RDS_HOST: bitwrap-postgres
      RDS_DB: bitwrap
      RDS_USER: bitwrap
      RDS_PASSWORD: bitwrap
      AMQP_USER: bitwrap
      AMQP_PASS: bitwrap
    depends_on:
      - rabbit
      - postgres
